name: flipshop
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.42
  csc_picker_plus: ^0.0.3
  gender_picker: ^1.1.0
  email_validator: ^3.0.0
  cached_network_image: ^3.4.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/

 